import { NodeDefinition } from '@/types/workflow'

export const defaultNodes: NodeDefinition[] = [
  // ══════════════════════════════════════════
  // TRIGGERS
  // ══════════════════════════════════════════
  {
    type: 'webhook',
    label: 'Webhook',
    description: 'Receive HTTP requests to start a workflow. Supports GET, POST, PUT, PATCH, DELETE.',
    category: 'trigger',
    inputs: 0,
    outputs: 1,
    configSchema: {
      method: { type: 'select', label: 'HTTP Method', description: 'Which HTTP method to listen for', default: 'POST', options: ['GET', 'POST', 'PUT', 'PATCH', 'DELETE'] },
      path: { type: 'string', label: 'Endpoint Path', description: 'The URL path suffix for this webhook', placeholder: '/hook/:id', default: '/hook/:id' },
      secret: { type: 'string', label: 'Secret Token', description: 'Optional secret for HMAC verification', placeholder: 'Leave blank for no verification', default: '' },
    },
    handles: [
      { id: 'output', type: 'source', position: 'right', label: 'Triggered', color: '#f59f00' },
    ],
  },
  {
    type: 'schedule',
    label: 'Schedule',
    description: 'Trigger on a cron or interval schedule. Runs at the specified time intervals.',
    category: 'trigger',
    inputs: 0,
    outputs: 1,
    configSchema: {
      cron: { type: 'string', label: 'Cron Expression', description: 'Standard cron syntax. Use tools like crontab.guru to generate.', placeholder: '0 */6 * * *', default: '0 */6 * * *' },
      timezone: { type: 'select', label: 'Timezone', description: 'Time zone for the schedule', default: 'UTC', options: ['UTC', 'US/Eastern', 'US/Pacific', 'Europe/London', 'Europe/Berlin', 'Asia/Tokyo', 'Asia/Shanghai'] },
      description: { type: 'string', label: 'Label', description: 'Human-readable label for this schedule', placeholder: 'Every 6 hours', default: '' },
    },
  },
  {
    type: 'form_submit',
    label: 'Form Submit',
    description: 'Triggered when a TspoonBase form or collection record is created.',
    category: 'trigger',
    inputs: 0,
    outputs: 1,
    configSchema: {
      collection: { type: 'string', label: 'Collection Name', description: 'The TspoonBase collection to watch', placeholder: 'articles', default: '' },
      operation: { type: 'select', label: 'Operation', description: 'Which operation triggers the workflow', default: 'create', options: ['create', 'update', 'delete'] },
    },
  },
  {
    type: 'email_in',
    label: 'Email Received',
    description: 'Trigger on incoming email to a monitored address. Supports IMAP polling.',
    category: 'trigger',
    inputs: 0,
    outputs: 1,
    configSchema: {
      address: { type: 'string', label: 'Email Address', description: 'The monitored email address', placeholder: 'workflow@example.com', default: '' },
      subjectFilter: { type: 'string', label: 'Subject Filter', description: 'Only trigger if subject contains this text', placeholder: 'Leave blank for all emails', default: '' },
      folder: { type: 'string', label: 'IMAP Folder', description: 'The mailbox folder to monitor', placeholder: 'INBOX', default: 'INBOX' },
    },
  },
  {
    type: 'db_watch',
    label: 'DB Watcher',
    description: 'Watch a SQL collection for changes using TspoonBase realtime subscriptions.',
    category: 'trigger',
    inputs: 0,
    outputs: 1,
    configSchema: {
      collection: { type: 'string', label: 'Collection', description: 'Collection to watch for realtime changes', placeholder: 'orders', default: '' },
      event: { type: 'select', label: 'Event Type', description: 'Which event triggers', default: '*', options: ['*', 'create', 'update', 'delete'] },
    },
  },
  {
    type: 'custom_event',
    label: 'Custom Event',
    description: 'Triggered by a custom named event fired from another workflow or external system.',
    category: 'trigger',
    inputs: 0,
    outputs: 1,
    configSchema: {
      eventName: { type: 'string', label: 'Event Name', description: 'Unique name for this custom event', placeholder: 'order.shipped', default: '' },
      payloadSchema: { type: 'code', label: 'Payload Schema (optional)', description: 'JSON schema to validate incoming event payloads', default: '{}' },
    },
  },
  {
    type: 'chat_trigger',
    label: 'Chat Message',
    description: 'Triggered by an incoming chat message from a widget, website embed, or API.',
    category: 'trigger',
    inputs: 0,
    outputs: 1,
    configSchema: {
      channel: { type: 'select', label: 'Channel', description: 'Which chat channel to listen on', default: 'widget', options: ['widget', 'api', 'slack', 'discord', 'whatsapp'] },
      endpoint: { type: 'string', label: 'Endpoint Path', description: 'Webhook path for chat messages', placeholder: '/chat/webhook', default: '/chat/webhook' },
      responseMode: { type: 'select', label: 'Response Mode', description: 'How to send the response back', default: 'realtime', options: ['realtime', 'webhook', 'poll'] },
    },
    handles: [
      { id: 'message', type: 'source', position: 'right', label: 'Message', color: '#f59f00' },
    ],
  },

  // ══════════════════════════════════════════
  // AI
  // ══════════════════════════════════════════
  {
    type: 'llm',
    label: 'LLM Chat',
    description: 'Send a prompt to an LLM and get a response. Supports system prompts, temperature control, and token limits.',
    category: 'ai',
    inputs: 1,
    outputs: 1,
    configSchema: {
      model: { type: 'select', label: 'Model', description: 'The LLM to use for generation', default: 'claude-sonnet-4-20250514', options: ['claude-sonnet-4-20250514', 'claude-haiku-3-5', 'claude-opus-4', 'gpt-4o', 'gpt-4o-mini', 'gpt-4.1', 'gpt-4.1-mini'] },
      systemPrompt: { type: 'text', label: 'System Prompt', description: 'System-level instructions that set the behavior and context for the model', placeholder: 'You are a helpful assistant.', default: 'You are a helpful assistant.' },
      temperature: { type: 'slider', label: 'Temperature', description: 'Controls randomness. Lower values = more deterministic.', default: 0.7, min: 0, max: 2, step: 0.1 },
      maxTokens: { type: 'number', label: 'Max Output Tokens', description: 'Maximum number of tokens in the response', default: 2048, min: 1, max: 128000 },
      userMessage: { type: 'text', label: 'User Message', description: 'The user message to send. Use {{input}} to reference upstream data.', placeholder: '{{input}}', default: '{{input}}' },
    },
    handles: [
      { id: 'prompt', type: 'target', position: 'left', label: 'Prompt', color: '#6c5ce7' },
      { id: 'memory', type: 'target', position: 'top', label: 'Memory', color: '#339af0' },
      { id: 'tools', type: 'target', position: 'bottom', label: 'Tools', color: '#40c057' },
      { id: 'response', type: 'source', position: 'right', label: 'Response', color: '#6c5ce7' },
      { id: 'stream', type: 'source', position: 'bottom', label: 'Stream', color: '#f59f00' },
    ],
  },
  {
    type: 'llm_vision',
    label: 'Vision',
    description: 'Analyze images with a vision-capable LLM. Supports image URLs and base64.',
    category: 'ai',
    inputs: 1,
    outputs: 1,
    configSchema: {
      model: { type: 'select', label: 'Vision Model', description: 'The vision-capable model', default: 'claude-sonnet-4-20250514', options: ['claude-sonnet-4-20250514', 'claude-haiku-3-5', 'gpt-4o', 'gpt-4o-mini'] },
      prompt: { type: 'text', label: 'Analysis Prompt', description: 'What to ask about the image(s)', default: 'Describe what you see in this image.' },
      imageSource: { type: 'select', label: 'Image Source', description: 'How to provide the image', default: 'url', options: ['url', 'base64', 'from_input'] },
      imageUrl: { type: 'string', label: 'Image URL', description: 'URL of the image to analyze', placeholder: 'https://example.com/image.jpg', default: '' },
      detail: { type: 'select', label: 'Detail Level', description: 'How much detail to extract', default: 'auto', options: ['auto', 'low', 'high'] },
    },
    handles: [
      { id: 'image', type: 'target', position: 'left', label: 'Image', color: '#6c5ce7' },
      { id: 'prompt', type: 'target', position: 'top', label: 'Prompt', color: '#6c5ce7' },
      { id: 'analysis', type: 'source', position: 'right', label: 'Analysis', color: '#6c5ce7' },
    ],
  },
  {
    type: 'llm_tool_use',
    label: 'Tool-Using Agent',
    description: 'LLM that can call tools/functions to complete a task. Define the available tools.',
    category: 'ai',
    inputs: 1,
    outputs: 1,
    configSchema: {
      model: { type: 'select', label: 'Model', description: 'The model for tool use', default: 'claude-sonnet-4-20250514', options: ['claude-sonnet-4-20250514', 'claude-haiku-3-5', 'gpt-4o', 'gpt-4o-mini'] },
      systemPrompt: { type: 'text', label: 'System Prompt', description: 'Instructions for the agent', default: 'You are a helpful assistant with access to tools.' },
      tools: { type: 'code', label: 'Tool Definitions', description: 'JSON array of tool/function definitions the agent can call', default: '[\n  {\n    "name": "search",\n    "description": "Search the web",\n    "parameters": {\n      "query": { "type": "string" }\n    }\n  }\n]' },
      maxIterations: { type: 'number', label: 'Max Tool Calls', description: 'Maximum number of tool calls per request', default: 10, min: 1, max: 50 },
    },
  },
  {
    type: 'embed',
    label: 'Embeddings',
    description: 'Generate vector embeddings from text input. Useful for semantic search and RAG.',
    category: 'ai',
    inputs: 1,
    outputs: 1,
    configSchema: {
      model: { type: 'select', label: 'Embedding Model', description: 'Model to use for generating embeddings', default: 'text-embedding-3-small', options: ['text-embedding-3-small', 'text-embedding-3-large', 'text-embedding-ada-002'] },
      input: { type: 'text', label: 'Input Text', description: 'Text to embed. Use {{input}} for upstream data.', default: '{{input}}' },
      dimensions: { type: 'number', label: 'Dimensions', description: 'Number of dimensions (leave 0 for model default)', default: 0, min: 0, max: 3072 },
    },
  },
  {
    type: 'classify',
    label: 'Classifier',
    description: 'Classify input text into predefined categories using an LLM.',
    category: 'ai',
    inputs: 1,
    outputs: 1,
    configSchema: {
      categories: { type: 'code', label: 'Categories', description: 'One category per line. The LLM will classify the input into one of these.', default: 'positive\nnegative\nneutral' },
      model: { type: 'select', label: 'Model', description: 'Model for classification', default: 'claude-haiku-3-5', options: ['claude-haiku-3-5', 'gpt-4o-mini'] },
      instructions: { type: 'text', label: 'Custom Instructions', description: 'Additional classification guidelines', default: 'Classify the sentiment of the input text.' },
    },
  },
  {
    type: 'extract',
    label: 'Extractor',
    description: 'Extract structured data from unstructured text using a JSON schema.',
    category: 'ai',
    inputs: 1,
    outputs: 1,
    configSchema: {
      schema: { type: 'code', label: 'Extraction Schema', description: 'JSON schema defining the data structure to extract. The LLM will populate this.', default: '{\n  "name": "",\n  "date": "",\n  "amount": 0,\n  "currency": "USD"\n}' },
      model: { type: 'select', label: 'Model', description: 'Model for extraction', default: 'claude-haiku-3-5', options: ['claude-haiku-3-5', 'gpt-4o-mini', 'claude-sonnet-4-20250514'] },
    },
  },
  {
    type: 'translate',
    label: 'Translate',
    description: 'Translate text between languages.',
    category: 'ai',
    inputs: 1,
    outputs: 1,
    configSchema: {
      sourceLang: { type: 'select', label: 'Source Language', description: 'Source language (auto-detect if not specified)', default: 'Auto-detect', options: ['Auto-detect', 'English', 'Spanish', 'French', 'German', 'Japanese', 'Chinese', 'Arabic', 'Portuguese', 'Russian', 'Korean'] },
      targetLang: { type: 'select', label: 'Target Language', description: 'Language to translate into', default: 'Spanish', options: ['Spanish', 'French', 'German', 'Japanese', 'Chinese', 'Arabic', 'Portuguese', 'Russian', 'Korean', 'English'] },
      preserveFormatting: { type: 'boolean', label: 'Preserve Formatting', description: 'Keep original formatting (markdown, line breaks, etc.)', default: true },
    },
  },
  {
    type: 'summarize',
    label: 'Summarize',
    description: 'Generate a concise summary of input text.',
    category: 'ai',
    inputs: 1,
    outputs: 1,
    configSchema: {
      maxLength: { type: 'slider', label: 'Max Summary Length', description: 'Target maximum length in words', default: 200, min: 20, max: 2000, step: 10 },
      style: { type: 'select', label: 'Summary Style', description: 'The style of the summary', default: 'concise', options: ['concise', 'detailed', 'bullet-points', 'tl-dr', 'executive'] },
      focus: { type: 'string', label: 'Focus Area', description: 'What to focus the summary on (optional)', placeholder: 'key findings, dates, decisions', default: '' },
    },
  },
  {
    type: 'llm_local',
    label: 'Local LLM',
    description: 'Run inference on a local LLM via Ollama, llama.cpp, or any OpenAI-compatible endpoint.',
    category: 'ai',
    inputs: 1,
    outputs: 1,
    configSchema: {
      endpoint: { type: 'string', label: 'Endpoint URL', description: 'URL of the local LLM server (Ollama, llama.cpp, vLLM)', placeholder: 'http://localhost:11434/v1/chat/completions', default: 'http://localhost:11434/v1/chat/completions' },
      model: { type: 'string', label: 'Model Name', description: 'Model name (e.g. llama3, mistral, codellama)', placeholder: 'llama3', default: 'llama3' },
      systemPrompt: { type: 'text', label: 'System Prompt', description: 'System-level instructions for the local model', default: 'You are a helpful assistant.' },
      temperature: { type: 'slider', label: 'Temperature', description: 'Controls randomness. Lower = more deterministic.', default: 0.7, min: 0, max: 2, step: 0.1 },
      maxTokens: { type: 'number', label: 'Max Output Tokens', description: 'Maximum tokens in the response', default: 2048, min: 1, max: 128000 },
    },
    handles: [
      { id: 'prompt', type: 'target', position: 'left', label: 'Prompt', color: '#6c5ce7' },
      { id: 'response', type: 'source', position: 'right', label: 'Response', color: '#6c5ce7' },
    ],
  },
  {
    type: 'llm_azure',
    label: 'Azure OpenAI',
    description: 'Call Azure OpenAI models with managed authentication and custom deployments.',
    category: 'ai',
    inputs: 1,
    outputs: 1,
    configSchema: {
      deployment: { type: 'string', label: 'Deployment Name', description: 'Azure OpenAI deployment name', placeholder: 'gpt-4o-deployment', default: '' },
      endpoint: { type: 'string', label: 'Azure Endpoint', description: 'Azure OpenAI resource endpoint', placeholder: 'https://my-resource.openai.azure.com', default: '' },
      apiKey: { type: 'string', label: 'API Key', description: 'Azure API key or use AZURE_OPENAI_API_KEY env var', default: '' },
      systemPrompt: { type: 'text', label: 'System Prompt', description: 'System-level instructions for the model', default: 'You are a helpful assistant.' },
      temperature: { type: 'slider', label: 'Temperature', description: 'Controls randomness', default: 0.7, min: 0, max: 2, step: 0.1 },
      maxTokens: { type: 'number', label: 'Max Output Tokens', description: 'Maximum tokens in the response', default: 2048, min: 1, max: 128000 },
    },
    handles: [
      { id: 'prompt', type: 'target', position: 'left', label: 'Prompt', color: '#6c5ce7' },
      { id: 'response', type: 'source', position: 'right', label: 'Response', color: '#6c5ce7' },
    ],
  },
  {
    type: 'llm_google',
    label: 'Google Gemini',
    description: 'Call Google Gemini models (Gemini 2.0 Flash, Gemini 2.0 Pro) via the Gemini API.',
    category: 'ai',
    inputs: 1,
    outputs: 1,
    configSchema: {
      model: { type: 'select', label: 'Model', description: 'Gemini model to use', default: 'gemini-2.0-flash', options: ['gemini-2.0-flash', 'gemini-2.0-pro', 'gemini-1.5-pro', 'gemini-1.5-flash'] },
      apiKey: { type: 'string', label: 'API Key', description: 'Google AI API key or use GOOGLE_API_KEY env var', default: '' },
      systemPrompt: { type: 'text', label: 'System Prompt', description: 'System instructions for Gemini', default: 'You are a helpful assistant.' },
      temperature: { type: 'slider', label: 'Temperature', description: 'Controls randomness', default: 0.7, min: 0, max: 2, step: 0.1 },
      maxTokens: { type: 'number', label: 'Max Output Tokens', description: 'Maximum tokens in the response', default: 2048, min: 1, max: 128000 },
    },
    handles: [
      { id: 'prompt', type: 'target', position: 'left', label: 'Prompt', color: '#6c5ce7' },
      { id: 'response', type: 'source', position: 'right', label: 'Response', color: '#6c5ce7' },
    ],
  },
  {
    type: 'llm_groq',
    label: 'Groq Cloud',
    description: 'Run fast inference on Groq hardware with Llama, Mixtral, and other open models.',
    category: 'ai',
    inputs: 1,
    outputs: 1,
    configSchema: {
      model: { type: 'select', label: 'Model', description: 'Groq-hosted model', default: 'llama-3.3-70b-versatile', options: ['llama-3.3-70b-versatile', 'llama-3.1-8b-instant', 'mixtral-8x7b-32768', 'gemma2-9b-it'] },
      apiKey: { type: 'string', label: 'API Key', description: 'Groq API key or use GROQ_API_KEY env var', default: '' },
      systemPrompt: { type: 'text', label: 'System Prompt', description: 'System-level instructions', default: 'You are a helpful assistant.' },
      temperature: { type: 'slider', label: 'Temperature', description: 'Controls randomness', default: 0.7, min: 0, max: 2, step: 0.1 },
      maxTokens: { type: 'number', label: 'Max Output Tokens', description: 'Maximum tokens in the response', default: 4096, min: 1, max: 128000 },
    },
    handles: [
      { id: 'prompt', type: 'target', position: 'left', label: 'Prompt', color: '#6c5ce7' },
      { id: 'response', type: 'source', position: 'right', label: 'Response', color: '#6c5ce7' },
    ],
  },
  {
    type: 'rag_search',
    label: 'RAG Search',
    description: 'Search vector embeddings for semantically similar documents.',
    category: 'ai',
    inputs: 1,
    outputs: 1,
    configSchema: {
      collection: { type: 'string', label: 'Vector Collection', description: 'The TspoonBase collection with vector embeddings', placeholder: 'documents', default: '' },
      query: { type: 'text', label: 'Search Query', description: 'The semantic search query', default: '{{input}}' },
      topK: { type: 'number', label: 'Top K Results', description: 'Number of results to return', default: 5, min: 1, max: 50 },
      minScore: { type: 'slider', label: 'Min Similarity Score', description: 'Minimum similarity threshold (0-1)', default: 0.7, min: 0, max: 1, step: 0.05 },
    },
  },
  {
    type: 'image_gen',
    label: 'Generate Image',
    description: 'Generate an image from a text description using a diffusion model.',
    category: 'ai',
    inputs: 1,
    outputs: 1,
    configSchema: {
      model: { type: 'select', label: 'Model', description: 'Image generation model', default: 'dall-e-3', options: ['dall-e-3', 'dall-e-2', 'stable-diffusion-xl'] },
      prompt: { type: 'text', label: 'Prompt', description: 'Description of the image to generate', default: '{{input}}' },
      size: { type: 'select', label: 'Image Size', description: 'Output image dimensions', default: '1024x1024', options: ['256x256', '512x512', '1024x1024', '1024x1792', '1792x1024'] },
      quality: { type: 'select', label: 'Quality', description: 'Image quality', default: 'standard', options: ['standard', 'hd'] },
    },
  },
  {
    type: 'audio_transcribe',
    label: 'Transcribe Audio',
    description: 'Transcribe audio to text using speech-to-text.',
    category: 'ai',
    inputs: 1,
    outputs: 1,
    configSchema: {
      model: { type: 'select', label: 'Model', description: 'Transcription model', default: 'whisper-1', options: ['whisper-1'] },
      language: { type: 'select', label: 'Language (optional)', description: 'Language hint for better accuracy', default: 'auto', options: ['auto', 'en', 'es', 'fr', 'de', 'ja', 'zh'] },
      responseFormat: { type: 'select', label: 'Output Format', description: 'Transcription output format', default: 'text', options: ['text', 'json', 'srt', 'vtt'] },
    },
  },

  // ══════════════════════════════════════════
  // DATA
  // ══════════════════════════════════════════
  {
    type: 'pocketbase_get',
    label: 'Get Record',
    description: 'Fetch a single record from a TspoonBase collection by ID.',
    category: 'data',
    inputs: 1,
    outputs: 1,
    configSchema: {
      collection: { type: 'string', label: 'Collection', description: 'The TspoonBase collection name', placeholder: 'articles', default: '' },
      recordId: { type: 'string', label: 'Record ID', description: 'The ID of the record to fetch. Use {{input}} for dynamic lookup.', placeholder: 'abc123 or {{input.id}}', default: '{{input.id}}' },
      expand: { type: 'string', label: 'Expand Fields', description: 'Comma-separated relation fields to expand', placeholder: 'author,category', default: '' },
    },
  },
  {
    type: 'pocketbase_list',
    label: 'List Records',
    description: 'Query a list of records from TspoonBase with filters, sorting, and pagination.',
    category: 'data',
    inputs: 1,
    outputs: 1,
    configSchema: {
      collection: { type: 'string', label: 'Collection', description: 'The TspoonBase collection name', placeholder: 'articles', default: '' },
      filter: { type: 'text', label: 'Filter Expression', description: 'TspoonBase filter syntax. Use variables with {{}}.', placeholder: 'status = "published"', default: '' },
      sort: { type: 'string', label: 'Sort', description: 'Sort field(s). Prefix with - for descending.', placeholder: '-created', default: '-created' },
      limit: { type: 'number', label: 'Page Limit', description: 'Max records per page', default: 50, min: 1, max: 500 },
      page: { type: 'number', label: 'Page Number', description: 'Page number for pagination', default: 1, min: 1 },
      expand: { type: 'string', label: 'Expand Fields', description: 'Comma-separated relation fields to expand', placeholder: 'author', default: '' },
    },
  },
  {
    type: 'pocketbase_create',
    label: 'Create Record',
    description: 'Create a new record in a TspoonBase collection.',
    category: 'data',
    inputs: 1,
    outputs: 1,
    configSchema: {
      collection: { type: 'string', label: 'Collection', description: 'The collection to create the record in', placeholder: 'articles', default: '' },
      data: { type: 'code', label: 'Record Data', description: 'JSON object with the record fields. Use {{input}} for dynamic values.', default: '{\n  "title": "{{input.title}}",\n  "content": "{{input.content}}"\n}' },
    },
  },
  {
    type: 'pocketbase_update',
    label: 'Update Record',
    description: 'Update an existing TspoonBase record by ID.',
    category: 'data',
    inputs: 1,
    outputs: 1,
    configSchema: {
      collection: { type: 'string', label: 'Collection', description: 'The collection containing the record', placeholder: 'articles', default: '' },
      recordId: { type: 'string', label: 'Record ID', description: 'ID of the record to update', placeholder: '{{input.id}}', default: '{{input.id}}' },
      data: { type: 'code', label: 'Update Data', description: 'JSON with fields to update', default: '{\n  "status": "published",\n  "updatedAt": "{{now}}" \n}' },
    },
  },
  {
    type: 'pocketbase_delete',
    label: 'Delete Record',
    description: 'Delete a TspoonBase record by ID.',
    category: 'data',
    inputs: 1,
    outputs: 1,
    configSchema: {
      collection: { type: 'string', label: 'Collection', description: 'The collection containing the record', placeholder: 'articles', default: '' },
      recordId: { type: 'string', label: 'Record ID', description: 'ID of the record to delete', placeholder: '{{input.id}}', default: '{{input.id}}' },
    },
  },
  {
    type: 'json_parse',
    label: 'Parse JSON',
    description: 'Parse a JSON string into an object for use in downstream nodes.',
    category: 'data',
    inputs: 1,
    outputs: 1,
    configSchema: {},
  },
  {
    type: 'transform',
    label: 'Transform',
    description: 'Transform data using a template with variable interpolation. Uses Handlebars-style {{variable}} syntax.',
    category: 'data',
    inputs: 1,
    outputs: 1,
    configSchema: {
      template: { type: 'code', label: 'Template', description: 'Template with {{variable}} placeholders. Access nested data with dot notation.', default: '{\n  "name": "{{input.name}}",\n  "email": "{{input.email}}",\n  "date": "{{now}}"\n}' },
      mode: { type: 'select', label: 'Mode', description: 'Transformation mode', default: 'template', options: ['template', 'javascript'] },
    },
  },
  {
    type: 'filter',
    label: 'Filter Array',
    description: 'Filter an array of items based on a condition expression.',
    category: 'data',
    inputs: 1,
    outputs: 1,
    configSchema: {
      arrayPath: { type: 'string', label: 'Array Path', description: 'Dot path to the array in the input', placeholder: 'input.items', default: 'input.items' },
      condition: { type: 'code', label: 'Filter Condition', description: 'Expression evaluated for each item. Return true to keep.', default: 'item.active === true' },
    },
  },
  {
    type: 'aggregate',
    label: 'Aggregate',
    description: 'Aggregate/group data from an array (sum, avg, count, min, max).',
    category: 'data',
    inputs: 1,
    outputs: 1,
    configSchema: {
      arrayPath: { type: 'string', label: 'Array Path', description: 'Dot path to the array data', placeholder: 'input.items', default: 'input.items' },
      operation: { type: 'select', label: 'Operation', description: 'Aggregation operation', default: 'sum', options: ['sum', 'avg', 'count', 'min', 'max', 'group-by'] },
      field: { type: 'string', label: 'Target Field', description: 'Field name to aggregate on (for sum/avg/min/max)', placeholder: 'amount', default: '' },
      groupBy: { type: 'string', label: 'Group By Field', description: 'Field to group by (for group-by operation)', placeholder: 'category', default: '' },
    },
  },
  {
    type: 'merge',
    label: 'Merge Data',
    description: 'Merge multiple input values into a single object or array.',
    category: 'data',
    inputs: 3,
    outputs: 1,
    configSchema: {
      strategy: { type: 'select', label: 'Merge Strategy', description: 'How to combine the inputs', default: 'object-merge', options: ['object-merge', 'array-concat', 'array-zip', 'overwrite'] },
    },
    handles: [
      { id: 'input_a', type: 'target', position: 'left', label: 'Source A', color: '#339af0' },
      { id: 'input_b', type: 'target', position: 'top', label: 'Source B', color: '#40c057' },
      { id: 'input_c', type: 'target', position: 'bottom', label: 'Source C', color: '#f59f00' },
      { id: 'output', type: 'source', position: 'right', label: 'Merged', color: '#339af0' },
    ],
  },
  {
    type: 'split',
    label: 'Split Array',
    description: 'Split an array into chunks or separate items.',
    category: 'data',
    inputs: 1,
    outputs: 1,
    configSchema: {
      arrayPath: { type: 'string', label: 'Array Path', description: 'Dot path to the array', placeholder: 'input.items', default: 'input.items' },
      chunkSize: { type: 'number', label: 'Chunk Size', description: 'Number of items per chunk (0 = individual items)', default: 0, min: 0, max: 1000 },
    },
  },
  {
    type: 'sort',
    label: 'Sort Data',
    description: 'Sort an array of items by a field.',
    category: 'data',
    inputs: 1,
    outputs: 1,
    configSchema: {
      arrayPath: { type: 'string', label: 'Array Path', description: 'Dot path to the array', placeholder: 'input.items', default: 'input.items' },
      sortField: { type: 'string', label: 'Sort Field', description: 'Field to sort by', placeholder: 'created', default: '' },
      order: { type: 'select', label: 'Order', description: 'Sort direction', default: 'asc', options: ['asc', 'desc'] },
    },
  },
  {
    type: 'deduplicate',
    label: 'Deduplicate',
    description: 'Remove duplicate items from an array based on a key field.',
    category: 'data',
    inputs: 1,
    outputs: 1,
    configSchema: {
      arrayPath: { type: 'string', label: 'Array Path', description: 'Dot path to the array', placeholder: 'input.items', default: 'input.items' },
      keyField: { type: 'string', label: 'Key Field', description: 'Field to use for deduplication', placeholder: 'id', default: 'id' },
    },
  },
  {
    type: 'neon_query',
    label: 'Neon Postgres',
    description: 'Execute SQL queries against a Neon serverless Postgres database.',
    category: 'data',
    inputs: 1,
    outputs: 1,
    configSchema: {
      connectionString: { type: 'string', label: 'Connection String', description: 'Neon Postgres connection string (postgres://...)', placeholder: 'postgres://user:pass@ep-xxx.us-east-2.aws.neon.tech/db', default: '' },
      query: { type: 'code', label: 'SQL Query', description: 'Parameterized SQL query. Use $1, $2 for variables.', default: 'SELECT * FROM users WHERE id = $1' },
      params: { type: 'code', label: 'Query Parameters', description: 'JSON array of parameter values', default: '["{{input.id}}"]' },
    },
    handles: [
      { id: 'input', type: 'target', position: 'left', label: 'Input', color: '#339af0' },
      { id: 'result', type: 'source', position: 'right', label: 'Result', color: '#339af0' },
      { id: 'error', type: 'source', position: 'bottom', label: 'Error', color: '#e03131' },
    ],
  },
  {
    type: 'mongodb_query',
    label: 'MongoDB',
    description: 'Query or mutate documents in a MongoDB collection.',
    category: 'data',
    inputs: 1,
    outputs: 1,
    configSchema: {
      uri: { type: 'string', label: 'MongoDB URI', description: 'MongoDB connection string', placeholder: 'mongodb+srv://user:pass@cluster.mongodb.net/db', default: '' },
      collection: { type: 'string', label: 'Collection', description: 'Collection name', placeholder: 'users', default: '' },
      operation: { type: 'select', label: 'Operation', description: 'Database operation to perform', default: 'find', options: ['find', 'findOne', 'insertOne', 'updateOne', 'deleteOne', 'aggregate'] },
      filter: { type: 'code', label: 'Query Filter', description: 'JSON filter document', default: '{"_id": "{{input.id}}"}' },
      data: { type: 'code', label: 'Data / Pipeline', description: 'Insert data, update document, or aggregation pipeline', default: '{}' },
    },
    handles: [
      { id: 'input', type: 'target', position: 'left', label: 'Input', color: '#339af0' },
      { id: 'result', type: 'source', position: 'right', label: 'Result', color: '#339af0' },
      { id: 'error', type: 'source', position: 'bottom', label: 'Error', color: '#e03131' },
    ],
  },
  {
    type: 'supabase_query',
    label: 'Supabase',
    description: 'Query a Supabase PostgreSQL database or invoke Edge Functions.',
    category: 'data',
    inputs: 1,
    outputs: 1,
    configSchema: {
      url: { type: 'string', label: 'Supabase URL', description: 'Supabase project URL', placeholder: 'https://xxxxx.supabase.co', default: '' },
      apiKey: { type: 'string', label: 'Service Role Key', description: 'Supabase service_role key (private, server-side only)', default: '' },
      table: { type: 'string', label: 'Table Name', description: 'Table to query', placeholder: 'users', default: '' },
      operation: { type: 'select', label: 'Operation', description: 'Database operation', default: 'select', options: ['select', 'insert', 'update', 'delete', 'rpc'] },
      filter: { type: 'code', label: 'Filter / Body', description: 'Query filter (select) or row data (insert/update)', default: '{"column": "value"}' },
    },
    handles: [
      { id: 'input', type: 'target', position: 'left', label: 'Input', color: '#339af0' },
      { id: 'result', type: 'source', position: 'right', label: 'Result', color: '#339af0' },
      { id: 'error', type: 'source', position: 'bottom', label: 'Error', color: '#e03131' },
    ],
  },
  {
    type: 'firebase_query',
    label: 'Firebase Firestore',
    description: 'Read or write documents in Firebase Firestore.',
    category: 'data',
    inputs: 1,
    outputs: 1,
    configSchema: {
      projectId: { type: 'string', label: 'Project ID', description: 'Firebase project ID', placeholder: 'my-project-id', default: '' },
      clientEmail: { type: 'string', label: 'Client Email', description: 'Firebase service account client email', default: '' },
      privateKey: { type: 'code', label: 'Private Key', description: 'Firebase service account private key', default: '' },
      collection: { type: 'string', label: 'Collection', description: 'Firestore collection path', placeholder: 'users', default: '' },
      operation: { type: 'select', label: 'Operation', description: 'Firestore operation', default: 'get', options: ['get', 'list', 'add', 'set', 'update', 'delete'] },
      docId: { type: 'string', label: 'Document ID', description: 'Document ID (for get/set/update/delete)', placeholder: '{{input.id}}', default: '{{input.id}}' },
      data: { type: 'code', label: 'Document Data', description: 'JSON data for write operations', default: '{"field": "value"}' },
    },
    handles: [
      { id: 'input', type: 'target', position: 'left', label: 'Input', color: '#339af0' },
      { id: 'result', type: 'source', position: 'right', label: 'Result', color: '#339af0' },
      { id: 'error', type: 'source', position: 'bottom', label: 'Error', color: '#e03131' },
    ],
  },

  // ══════════════════════════════════════════
  // ACTIONS
  // ══════════════════════════════════════════
  {
    type: 'http_request',
    label: 'HTTP Request',
    description: 'Make an HTTP request to an external API. Supports all methods, custom headers, and body.',
    category: 'action',
    inputs: 1,
    outputs: 1,
    configSchema: {
      method: { type: 'select', label: 'Method', description: 'HTTP method for the request', default: 'GET', options: ['GET', 'POST', 'PUT', 'PATCH', 'DELETE'] },
      url: { type: 'string', label: 'URL', description: 'The full URL including query params. Use {{input}} for dynamic parts.', placeholder: 'https://api.example.com/data', default: '' },
      headers: { type: 'code', label: 'Headers', description: 'JSON object of HTTP headers', default: '{\n  "Content-Type": "application/json",\n  "Authorization": "Bearer {{input.token}}"\n}' },
      body: { type: 'code', label: 'Request Body', description: 'Request body (for POST/PUT/PATCH). Ignored for GET/DELETE.', default: '' },
      timeout: { type: 'number', label: 'Timeout (ms)', description: 'Request timeout in milliseconds', default: 30000, min: 1000, max: 300000 },
      retryOnFailure: { type: 'boolean', label: 'Retry on Failure', description: 'Automatically retry on 5xx or network errors', default: true },
    },
    handles: [
      { id: 'input', type: 'target', position: 'left', label: 'Input', color: '#40c057' },
      { id: 'config', type: 'target', position: 'top', label: 'Config', color: '#339af0' },
      { id: 'response', type: 'source', position: 'right', label: 'Response', color: '#40c057' },
      { id: 'error', type: 'source', position: 'bottom', label: 'Error', color: '#e03131' },
    ],
  },
  {
    type: 'graphql',
    label: 'GraphQL Query',
    description: 'Execute a GraphQL query against an endpoint.',
    category: 'action',
    inputs: 1,
    outputs: 1,
    configSchema: {
      endpoint: { type: 'string', label: 'GraphQL Endpoint', description: 'URL of the GraphQL API', placeholder: 'https://api.example.com/graphql', default: '' },
      query: { type: 'code', label: 'Query/Mutation', description: 'The GraphQL query or mutation', default: 'query($id: ID!) {\n  item(id: $id) {\n    id\n    name\n  }\n}' },
      variables: { type: 'code', label: 'Variables', description: 'JSON variables for the query', default: '{\n  "id": "{{input.id}}"\n}' },
    },
    handles: [
      { id: 'input', type: 'target', position: 'left', label: 'Input', color: '#40c057' },
      { id: 'result', type: 'source', position: 'right', label: 'Result', color: '#40c057' },
      { id: 'error', type: 'source', position: 'bottom', label: 'Error', color: '#e03131' },
    ],
  },
  {
    type: 'send_email',
    label: 'Send Email',
    description: 'Send an email via SMTP or TspoonBase mailer.',
    category: 'action',
    inputs: 1,
    outputs: 1,
    configSchema: {
      to: { type: 'string', label: 'To', description: 'Recipient email address(es). Comma-separated for multiple.', placeholder: 'user@example.com', default: '' },
      subject: { type: 'string', label: 'Subject', description: 'Email subject line', placeholder: 'Workflow completed', default: '' },
      body: { type: 'text', label: 'Email Body', description: 'Plain text or HTML body. Use {{input}} for dynamic content.', default: '' },
      cc: { type: 'string', label: 'CC', description: 'CC recipients (comma-separated)', placeholder: '', default: '' },
      bcc: { type: 'string', label: 'BCC', description: 'BCC recipients (comma-separated)', placeholder: '', default: '' },
    },
  },
  {
    type: 'push_notification',
    label: 'Push Notification',
    description: 'Send a push notification to devices or channels.',
    category: 'action',
    inputs: 1,
    outputs: 1,
    configSchema: {
      title: { type: 'string', label: 'Title', description: 'Notification title', placeholder: 'Workflow Update', default: '' },
      body: { type: 'text', label: 'Body', description: 'Notification message body', default: '' },
      channel: { type: 'select', label: 'Channel', description: 'Delivery channel', default: 'all', options: ['all', 'web', 'mobile', 'email'] },
      priority: { type: 'select', label: 'Priority', description: 'Notification priority', default: 'normal', options: ['normal', 'high', 'urgent'] },
    },
  },
  {
    type: 'slack_message',
    label: 'Slack Message',
    description: 'Post a message to a Slack channel via webhook.',
    category: 'action',
    inputs: 1,
    outputs: 1,
    configSchema: {
      webhookUrl: { type: 'string', label: 'Webhook URL', description: 'Slack incoming webhook URL', placeholder: 'https://hooks.slack.com/services/...', default: '' },
      channel: { type: 'string', label: 'Channel', description: 'Slack channel to post to (overrides webhook default)', placeholder: '#general', default: '#general' },
      message: { type: 'text', label: 'Message', description: 'Message text. Supports Slack markdown.', default: 'Hello from Torque workflow!' },
      username: { type: 'string', label: 'Bot Name', description: 'Custom bot name for the message', placeholder: 'Torque Bot', default: 'Torque Bot' },
    },
  },
  {
    type: 'discord_message',
    label: 'Discord Message',
    description: 'Post a message to a Discord channel via webhook.',
    category: 'action',
    inputs: 1,
    outputs: 1,
    configSchema: {
      webhookUrl: { type: 'string', label: 'Webhook URL', description: 'Discord webhook URL', placeholder: 'https://discord.com/api/webhooks/...', default: '' },
      message: { type: 'text', label: 'Message', description: 'Message content', default: 'Hello from Torque workflow!' },
      username: { type: 'string', label: 'Bot Name', description: 'Override the bot display name', default: '' },
      avatarUrl: { type: 'string', label: 'Avatar URL', description: 'Override the bot avatar', default: '' },
    },
  },
  {
    type: 'sms_twilio',
    label: 'Send SMS (Twilio)',
    description: 'Send an SMS message via Twilio.',
    category: 'action',
    inputs: 1,
    outputs: 1,
    configSchema: {
      to: { type: 'string', label: 'To Number', description: 'Recipient phone number (E.164 format)', placeholder: '+15551234567', default: '' },
      from: { type: 'string', label: 'From Number', description: 'Your Twilio phone number', placeholder: '+15559876543', default: '' },
      body: { type: 'text', label: 'Message Body', description: 'SMS message content', default: 'Hello from Torque!' },
    },
  },
  {
    type: 'github_action',
    label: 'GitHub Action',
    description: 'Trigger a GitHub Actions workflow or create an issue/PR.',
    category: 'action',
    inputs: 1,
    outputs: 1,
    configSchema: {
      token: { type: 'string', label: 'GitHub Token', description: 'Personal access token with repo scope', default: '' },
      repo: { type: 'string', label: 'Repository', description: 'Full repo name (owner/repo)', placeholder: 'owner/repo', default: '' },
      action: { type: 'select', label: 'Action Type', description: 'What GitHub action to perform', default: 'dispatch', options: ['dispatch', 'create-issue', 'create-pr-comment'] },
      eventType: { type: 'string', label: 'Event Type', description: 'Workflow dispatch event type', placeholder: 'deploy', default: 'torque-trigger' },
      payload: { type: 'code', label: 'Payload', description: 'JSON payload for the dispatch event', default: '{\n  "workflow": "{{input.name}}"\n}' },
    },
  },
  {
    type: 'notion_create',
    label: 'Notion - Create Page',
    description: 'Create a new page in a Notion database.',
    category: 'action',
    inputs: 1,
    outputs: 1,
    configSchema: {
      token: { type: 'string', label: 'Integration Token', description: 'Notion internal integration token', default: '' },
      databaseId: { type: 'string', label: 'Database ID', description: 'The Notion database ID (32-char UUID)', placeholder: 'abc...', default: '' },
      properties: { type: 'code', label: 'Page Properties', description: 'JSON matching the database schema', default: '{\n  "Name": { "title": [{ "text": { "content": "{{input.title}}" } }] },\n  "Status": { "select": { "name": "In Progress" } }\n}' },
    },
  },
  {
    type: 'file_upload',
    label: 'File Upload',
    description: 'Upload a file to TspoonBase file storage.',
    category: 'action',
    inputs: 1,
    outputs: 1,
    configSchema: {
      collection: { type: 'string', label: 'Collection', description: 'Collection with file field', placeholder: 'uploads', default: '' },
      field: { type: 'string', label: 'File Field Name', description: 'The file field name in the collection', placeholder: 'file', default: 'file' },
      filename: { type: 'string', label: 'Filename', description: 'Name for the uploaded file', placeholder: 'document.pdf', default: '' },
    },
  },
  {
    type: 'webhook_send',
    label: 'Send Webhook',
    description: 'Send an outgoing webhook to an external system.',
    category: 'action',
    inputs: 1,
    outputs: 1,
    configSchema: {
      url: { type: 'string', label: 'Webhook URL', description: 'The destination webhook URL', placeholder: 'https://hooks.example.com/event', default: '' },
      method: { type: 'select', label: 'HTTP Method', description: 'HTTP method to use', default: 'POST', options: ['POST', 'PUT', 'PATCH'] },
      payload: { type: 'code', label: 'Payload', description: 'JSON payload to send', default: '{{ input }}' },
      headers: { type: 'code', label: 'Custom Headers', description: 'Additional headers (JSON object)', default: '{}' },
    },
    handles: [
      { id: 'input', type: 'target', position: 'left', label: 'Payload', color: '#40c057' },
      { id: 'success', type: 'source', position: 'right', label: 'Sent', color: '#40c057' },
      { id: 'error', type: 'source', position: 'bottom', label: 'Failed', color: '#e03131' },
    ],
  },
  {
    type: 'pdf_generate',
    label: 'Generate PDF',
    description: 'Generate a PDF document from HTML content or a template.',
    category: 'action',
    inputs: 1,
    outputs: 1,
    configSchema: {
      html: { type: 'code', label: 'HTML Content', description: 'HTML content to render as PDF', default: '<h1>{{input.title}}</h1>\n<p>{{input.content}}</p>' },
      filename: { type: 'string', label: 'Output Filename', description: 'Name of the generated PDF file', placeholder: 'output.pdf', default: 'document.pdf' },
      format: { type: 'select', label: 'Page Size', description: 'PDF page size', default: 'A4', options: ['A4', 'Letter', 'Legal'] },
    },
  },
  {
    type: 'cloudinary_upload',
    label: 'Cloudinary Upload',
    description: 'Upload images, videos, or files to Cloudinary with transformation options.',
    category: 'action',
    inputs: 1,
    outputs: 1,
    configSchema: {
      cloudName: { type: 'string', label: 'Cloud Name', description: 'Your Cloudinary cloud name', placeholder: 'mycloud', default: '' },
      apiKey: { type: 'string', label: 'API Key', description: 'Cloudinary API key', default: '' },
      apiSecret: { type: 'string', label: 'API Secret', description: 'Cloudinary API secret', default: '' },
      fileUrl: { type: 'string', label: 'File URL', description: 'URL of the file to upload', placeholder: 'https://example.com/image.jpg', default: '' },
      folder: { type: 'string', label: 'Folder', description: 'Cloudinary folder to upload into', placeholder: 'uploads', default: 'torque' },
      transformations: { type: 'code', label: 'Transformations', description: 'Cloudinary transformation parameters (JSON)', default: '{"width": 800, "crop": "limit"}' },
    },
    handles: [
      { id: 'input', type: 'target', position: 'left', label: 'File', color: '#40c057' },
      { id: 'result', type: 'source', position: 'right', label: 'URL', color: '#40c057' },
      { id: 'error', type: 'source', position: 'bottom', label: 'Error', color: '#e03131' },
    ],
  },

  // ══════════════════════════════════════════
  // LOGIC
  // ══════════════════════════════════════════
  {
    type: 'condition',
    label: 'Condition',
    description: 'Branch execution based on a true/false condition. Routes to output 0 (true) or 1 (false).',
    category: 'logic',
    inputs: 1,
    outputs: 2,
    configSchema: {
      expression: { type: 'code', label: 'Condition Expression', description: 'Expression that returns true or false. Access data with dot notation.', default: 'input.value > 10' },
      trueLabel: { type: 'string', label: 'True Label', description: 'Label for the true/output_0 branch', placeholder: 'Valid', default: 'Yes' },
      falseLabel: { type: 'string', label: 'False Label', description: 'Label for the false/output_1 branch', placeholder: 'Invalid', default: 'No' },
    },
    handles: [
      { id: 'input', type: 'target', position: 'left', label: 'Input', color: '#e03131' },
      { id: 'true', type: 'source', position: 'right', label: 'True', color: '#40c057' },
      { id: 'false', type: 'source', position: 'bottom', label: 'False', color: '#e03131' },
    ],
  },
  {
    type: 'switch',
    label: 'Switch',
    description: 'Multi-branch routing based on value matching against defined cases.',
    category: 'logic',
    inputs: 1,
    outputs: 5,
    configSchema: {
      field: { type: 'string', label: 'Field Path', description: 'Path to the value to switch on', placeholder: 'input.status', default: 'input.status' },
      cases: { type: 'code', label: 'Case Definitions', description: 'JSON map of case value to output index', default: '{\n  "active": 0,\n  "pending": 1,\n  "completed": 2,\n  "failed": 3\n}' },
      defaultOutput: { type: 'number', label: 'Default Output', description: 'Output index if no case matches (0-4)', default: 4, min: 0, max: 4 },
    },
    handles: [
      { id: 'input', type: 'target', position: 'left', label: 'Input', color: '#e03131' },
      { id: 'case_0', type: 'source', position: 'right', label: 'Case 1', color: '#40c057' },
      { id: 'case_1', type: 'source', position: 'bottom', label: 'Case 2', color: '#339af0' },
      { id: 'case_2', type: 'source', position: 'bottom', label: 'Case 3', color: '#f59f00' },
      { id: 'default', type: 'source', position: 'right', label: 'Default', color: '#9898b0' },
    ],
  },
  {
    type: 'loop',
    label: 'For Each',
    description: 'Iterate over an array and process each item through connected nodes.',
    category: 'logic',
    inputs: 1,
    outputs: 2,
    configSchema: {
      collectionPath: { type: 'string', label: 'Array Path', description: 'Dot path to the array to iterate over', placeholder: 'input.items', default: 'input.items' },
      outputMode: { type: 'select', label: 'Output Mode', description: 'How to emit items', default: 'sequential', options: ['sequential', 'parallel', 'batch'] },
      batchSize: { type: 'number', label: 'Batch Size', description: 'Items per batch (for batch mode)', default: 10, min: 1, max: 100 },
      maxConcurrency: { type: 'number', label: 'Max Concurrency', description: 'Max parallel items (for parallel mode)', default: 5, min: 1, max: 50 },
    },
    handles: [
      { id: 'input', type: 'target', position: 'left', label: 'Array', color: '#e03131' },
      { id: 'item', type: 'source', position: 'right', label: 'Each Item', color: '#40c057' },
      { id: 'done', type: 'source', position: 'bottom', label: 'Complete', color: '#9898b0' },
    ],
  },
  {
    type: 'delay',
    label: 'Delay',
    description: 'Pause workflow execution for a specified duration.',
    category: 'logic',
    inputs: 1,
    outputs: 1,
    configSchema: {
      seconds: { type: 'number', label: 'Delay Duration', description: 'Time to wait in seconds', default: 5, min: 0, max: 86400 },
      jitter: { type: 'boolean', label: 'Add Jitter', description: 'Add random +/- 10% jitter to avoid thundering herd', default: false },
    },
    handles: [
      { id: 'input', type: 'target', position: 'left', label: 'Input', color: '#e03131' },
      { id: 'output', type: 'source', position: 'right', label: 'After Delay', color: '#f59f00' },
    ],
  },
  {
    type: 'code',
    label: 'Custom Code',
    description: 'Execute custom JavaScript code. Access input via the `input` variable.',
    category: 'logic',
    inputs: 1,
    outputs: 1,
    configSchema: {
      code: { type: 'code', label: 'JavaScript Code', description: 'Execute custom JS. Use `input` for upstream data, `return` to pass data downstream.', default: '// Transform input\nconst result = {\n  processed: true,\n  data: input,\n  timestamp: new Date().toISOString()\n};\nreturn result;' },
      timeout: { type: 'number', label: 'Timeout (ms)', description: 'Execution timeout', default: 5000, min: 100, max: 60000 },
    },
    handles: [
      { id: 'input', type: 'target', position: 'left', label: 'Input', color: '#e03131' },
      { id: 'result', type: 'source', position: 'right', label: 'Result', color: '#40c057' },
    ],
  },
  {
    type: 'retry',
    label: 'Retry',
    description: 'Wrap a sub-branch with retry logic and exponential backoff.',
    category: 'logic',
    inputs: 1,
    outputs: 2,
    configSchema: {
      maxRetries: { type: 'number', label: 'Max Retries', description: 'Maximum number of retry attempts', default: 3, min: 0, max: 10 },
      backoffMs: { type: 'number', label: 'Base Backoff (ms)', description: 'Initial backoff in milliseconds (doubles each retry)', default: 1000, min: 100, max: 60000 },
      retryOn: { type: 'multi-select', label: 'Retry On', description: 'Which error types trigger a retry', default: 'timeout,server_error', options: ['timeout', 'server_error', 'network_error', 'rate_limit', 'any'] },
    },
    handles: [
      { id: 'input', type: 'target', position: 'left', label: 'Input', color: '#e03131' },
      { id: 'success', type: 'source', position: 'right', label: 'Result', color: '#40c057' },
      { id: 'failed', type: 'source', position: 'bottom', label: 'Exhausted', color: '#e03131' },
    ],
  },
  {
    type: 'try_catch',
    label: 'Try / Catch',
    description: 'Handle errors gracefully. Output 0 = success path, output 1 = error path.',
    category: 'logic',
    inputs: 1,
    outputs: 2,
    configSchema: {
      errorMessage: { type: 'string', label: 'Error Message Template', description: 'Template for the error message sent to the catch output', placeholder: 'Error: {{error.message}}', default: '{{error.message}}' },
    },
    handles: [
      { id: 'input', type: 'target', position: 'left', label: 'Try', color: '#e03131' },
      { id: 'success', type: 'source', position: 'right', label: 'Success', color: '#40c057' },
      { id: 'catch', type: 'source', position: 'bottom', label: 'Error', color: '#e03131' },
    ],
  },
  {
    type: 'parallel',
    label: 'Parallel',
    description: 'Execute multiple downstream branches in parallel and wait for all to complete.',
    category: 'logic',
    inputs: 1,
    outputs: 1,
    configSchema: {
      maxConcurrency: { type: 'number', label: 'Max Concurrency', description: 'Maximum parallel executions', default: 10, min: 1, max: 100 },
      timeout: { type: 'number', label: 'Timeout (s)', description: 'Max time to wait for all branches', default: 60, min: 1, max: 3600 },
      failBehavior: { type: 'select', label: 'On Failure', description: 'What to do if a branch fails', default: 'wait-all', options: ['wait-all', 'cancel-others', 'ignore-errors'] },
    },
    handles: [
      { id: 'input', type: 'target', position: 'left', label: 'Input', color: '#e03131' },
      { id: 'branch_1', type: 'source', position: 'right', label: 'Branch A', color: '#40c057' },
      { id: 'branch_2', type: 'source', position: 'bottom', label: 'Branch B', color: '#339af0' },
      { id: 'branch_3', type: 'source', position: 'right', label: 'Branch C', color: '#f59f00' },
    ],
  },
  {
    type: 'throttle',
    label: 'Throttle',
    description: 'Rate-limit execution to prevent downstream overload.',
    category: 'logic',
    inputs: 1,
    outputs: 1,
    configSchema: {
      maxRequests: { type: 'number', label: 'Max Executions', description: 'Maximum number of executions', default: 10, min: 1, max: 10000 },
      perSeconds: { type: 'number', label: 'Per (seconds)', description: 'Time window in seconds', default: 1, min: 1, max: 3600 },
      key: { type: 'string', label: 'Rate Limit Key', description: 'Optional key to scope rate limiting', placeholder: 'default', default: '' },
    },
  },
  {
    type: 'dedup_events',
    label: 'Deduplicate Events',
    description: 'Prevent duplicate event processing within a time window.',
    category: 'logic',
    inputs: 1,
    outputs: 2,
    configSchema: {
      dedupKey: { type: 'string', label: 'Dedup Key', description: 'Expression to generate dedup key from input', placeholder: 'input.id', default: 'input.id' },
      windowMs: { type: 'number', label: 'Window (ms)', description: 'Time window in milliseconds', default: 60000, min: 1000, max: 86400000 },
    },
    handles: [
      { id: 'input', type: 'target', position: 'left', label: 'Event', color: '#e03131' },
      { id: 'unique', type: 'source', position: 'right', label: 'New', color: '#40c057' },
      { id: 'duplicate', type: 'source', position: 'bottom', label: 'Duplicate', color: '#9898b0' },
    ],
  },

  // ══════════════════════════════════════════
  // OUTPUT
  // ══════════════════════════════════════════
  {
    type: 'log',
    label: 'Log Output',
    description: 'Log data to the execution log. Useful for debugging and monitoring.',
    category: 'output',
    inputs: 1,
    outputs: 0,
    configSchema: {
      message: { type: 'text', label: 'Log Message', description: 'Message to log. Use {{input}} to reference upstream data.', default: '{{ input }}' },
      level: { type: 'select', label: 'Log Level', description: 'Severity level of the log entry', default: 'info', options: ['debug', 'info', 'warn', 'error'] },
    },
  },
  {
    type: 'webhook_response',
    label: 'Webhook Response',
    description: 'Send a response back to the webhook caller. Use at the end of webhook-triggered workflows.',
    category: 'output',
    inputs: 1,
    outputs: 0,
    configSchema: {
      statusCode: { type: 'number', label: 'HTTP Status', description: 'HTTP status code to return', default: 200, min: 100, max: 599 },
      body: { type: 'code', label: 'Response Body', description: 'JSON response body', default: '{\n  "success": true,\n  "data": {{input}}\n}' },
      headers: { type: 'code', label: 'Response Headers', description: 'Additional response headers', default: '{\n  "X-Workflow-Id": "{{workflow.id}}"\n}' },
    },
  },
  {
    type: 'export_csv',
    label: 'Export CSV',
    description: 'Export data as a CSV file and optionally save to storage.',
    category: 'output',
    inputs: 1,
    outputs: 0,
    configSchema: {
      filename: { type: 'string', label: 'Filename', description: 'Name of the exported CSV file', placeholder: 'export.csv', default: 'export.csv' },
      data: { type: 'code', label: 'Data Array', description: 'Array of objects to export as CSV rows', default: '{{input.items || [input]}}' },
      columns: { type: 'code', label: 'Column Mapping', description: 'Array of column definitions or JSON paths', default: '["name", "email", "date"]' },
      includeHeaders: { type: 'boolean', label: 'Include Headers', description: 'Include column headers as the first row', default: true },
    },
  },
  {
    type: 'save_record',
    label: 'Save to Collection',
    description: 'Persist data to a TspoonBase collection as a new record.',
    category: 'output',
    inputs: 1,
    outputs: 1,
    configSchema: {
      collection: { type: 'string', label: 'Collection', description: 'Target collection name', placeholder: 'results', default: '' },
      data: { type: 'code', label: 'Data to Save', description: 'JSON data to save. Use {{input}} to reference upstream.', default: '{{ input }}' },
    },
  },
  {
    type: 'return_data',
    label: 'Return Data',
    description: 'Return data from the workflow execution. Acts as the workflow output.',
    category: 'output',
    inputs: 1,
    outputs: 0,
    configSchema: {
      data: { type: 'code', label: 'Return Data', description: 'Data to return from the workflow', default: '{{ input }}' },
      format: { type: 'select', label: 'Response Format', description: 'Output format', default: 'json', options: ['json', 'text', 'raw'] },
    },
  },
  {
    type: 'webhook_slack',
    label: 'Slack Webhook',
    description: 'Post rich messages to Slack using Block Kit.',
    category: 'output',
    inputs: 1,
    outputs: 0,
    configSchema: {
      webhookUrl: { type: 'string', label: 'Webhook URL', description: 'Slack incoming webhook URL', placeholder: 'https://hooks.slack.com/services/...', default: '' },
      blocks: { type: 'code', label: 'Block Kit JSON', description: 'Slack Block Kit JSON payload', default: '{\n  "text": "Workflow completed!",\n  "blocks": [\n    {\n      "type": "section",\n      "text": {\n        "type": "mrkdwn",\n        "text": "✅ Workflow *{{workflow.name}}* completed successfully!"\n      }\n    }\n  ]\n}' },
    },
  },
]
